apiVersion: v1
kind: Service
metadata:
  name: go-demo-2-db
spec:
# there is no type: NodePort -> means that tha ports could be visible withing the cluster only
  ports:
    - port: 27017
  selector:
    type: db
    service: go-demo-2
